### PR TITLE
Fix bug with multi-select field

### PR DESCRIPTION
**Pull request by okopny**
I tried to use the multi-select field, but I came across a problem that only the last selected parameter remains

### CODE REVIEW

**Comment by oberix** [comment]
Hi @okopny, 
you are right about the bug, gut your patch seems to brake the form validation in a way that I didn't understand yet.

**Comment by okopny** [comment]
Hi @oberix, 
Hmmm, can you show me in which way the form validation is broken? I've tested the form validation and everything work well.

**Comment by oberix** [comment]
Hi @okopny,

sorry I had a bug in my testing project. Your patch is working correctly, merged. Also I removed the attribute `self.params` which is useless at this point.

Could you double test please, if it's working good for you too I'll make a new tag.

Thanks

**Comment by okopny** [comment]
I created a simple report for testing
```
from django import forms
from admin_reports import Report, register


class TestReportForm(forms.Form):
    action_from = forms.DateField()
    action_to = forms.DateField()
    aggregated_by = forms.ChoiceField(choices=[[None, 'None'], ['daily', 'Day'], ['monthly', 'Month']])
    country = forms.MultipleChoiceField(choices=[['us', 'US'], ['au', 'AU'], ['gb', 'GB']])


@register()
class TestReport(Report):
    form_class = TestReportForm

    def aggregate(self, **kwargs):
        return []
```




Requests:

- **/**


- **/?action_from=2020-20-20&action_to=aaaa&aggregated_by=value&country=fr**


- **/?action_from=2017-10-03&action_to=2017-10-04&aggregated_by=daily&country=us&country=au**

**Comment by okopny** [comment]
Cool! I've tested code on my own project and everything work perfectly. I think you can add new tag. Thanks a lot!

**Comment by oberix** [comment]
new tag v0.10.8 ready

**Pull request merged**
